`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company:
// Engineer:
//
// Create Date: 09/13/2026 02:21:46 PM
// Design Name: Nguyen Duc Toan
// Module Name: Controller
// Project Name: RV32I
// Target Devices:
// Tool Versions:
// Description:
//
// Dependencies:
//
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
//
//////////////////////////////////////////////////////////////////////////////////


module Controller(
    // Input t?ng Decode (ID)
    input logic [6:0] opcode,
    input logic [2:0] funct3D, // instrD[14:12]
    input logic funct7,        // instrD[30]

    // Input t? Pipeline Register truy?n sang t?ng Execute (EX)
    input logic branchE,
    input logic jumpE,
    input logic [2:0] funct3E,
    input logic ZeroE,
    input logic LessE,
    input logic BranchTakenE,

    // Output cho t?ng Decode (ID)
    output logic regwriteD,
    output logic [2:0] ImmSrcD,
    output logic alu_srcD,
    output logic memwriteD,
    output logic [1:0] result_srcD,
    output logic branchD,
    output logic jumpD,
    output logic [3:0] ALUcontrolD,

    // Output cho t?ng Execute (EX)
    output logic PCSrcE
    );

    logic [1:0] alu_opD;

    // 1. Khoi Main Decoder (Giai ma tai tang Decode)
    Main_decoder main_de(
        .opcode(opcode),
        .reg_write(regwriteD),
        .ImmSrc(ImmSrcD),
        .alu_src(alu_srcD),
        .mem_write(memwriteD),
        .result_src(result_srcD),
        .branch(branchD),
        .jump(jumpD),
        .alu_op(alu_opD)
    );

    // 2. Khoi ALU Decoder (Giai ma tai tang Decode)
    Alu_decoder ald_de(
        .opb5(opcode[5]),
        .funct3(funct3D),
        .funct7(funct7),
        .alu_op(alu_opD),
        .ALUcontrol(ALUcontrolD)
    );

    // Branch decision is generated by branch_compare in EX
    assign PCSrcE = BranchTakenE | jumpE;

endmodule
